
import { Geist, Geist_Mono, Inter, Merriweather } from "next/font/google";
import "./globals.css";
import { SessionProvider } from 'next-auth/react';
import Providers from "./components/Providers";
import { AppProvider } from "./context/AppContext.js";
import FindJobProvider from "./context/FindJob";
import { CareFormProvider } from './context/CareFormContext';
import { AuthProvider } from './context/AuthContext';
import SidebarMobile from "./components/SidebarMobile"
import { SocketProvider } from './context/SocketContext';

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const merriweather = Merriweather({
  variable: "--font-merriweather",
  weight: ["400", "700"], // Specify weights you want to use
  subsets: ["latin"],
});

export const metadata = {
  title: "Care For India",
  description: "Generated by create next app",
  icons: {
    icon: '/Icons/heartlogo.png',  // Simplified version
    apple: '/Icons/heartlogo.png'  // Also add Apple icon support
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${geistSans.variable} ${geistMono.variable} ${merriweather.variable} antialiased`}
      >
        
        <CareFormProvider>
        <FindJobProvider>
          <AppProvider>
            <Providers>
            <SocketProvider>
            <AuthProvider>
            {children}
            </AuthProvider>
            </SocketProvider>
            </Providers>
          </AppProvider>
        </FindJobProvider>
        </CareFormProvider>
      </body>
    </html>
  );
}
